version: '2'

services:
  app:
    container_name: NutritymAPP
    build: .
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
        - SERVER.PORT=8080
        - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/compose-postgres
        - SPRING.DATASOURCE.USERNAME=compose-postgres
        - SPRING.DATASOURCE.PASSWORD=compose-postgres
        - SPRING.JPA.DEFERDATASOURCEINITIALIZATION=TRUE
        - SPRING.DATASOURCE.DRIVERCLASSNAME=org.postgresql.Driver
        - SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.PostgreSQLDialect
        - SPRING.JPA.GENERATE-DDL=true
        - SPRING.JPA.SHOW-SQL=true
        - SPRING.DATASOURCE.SQL-SCRIPT-ENCODING=UTF-8
        - SPRING.JPA.HIBERNATE.DDL-AUTO=update
        - SPRING.DATASOURCE.INITIALIZATION-MODE=always
        - SPRING.DATASOURCE.HIKARI.AUTO-COMMIT=false
          
  db:
    image: 'postgres:latest'
    container_name: NutritymDB
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres